### ISSUE TITLE
Bazarr without permission to save substitles in /movies folder

### ISSUE THREAD

**Issue by rmacario** [GreenFrogSB/LMDS#20]
Hello, 

I'm facing the follow error when trying to download a movie subtitle from bazarr:
```
2021-09-17 03:00:03,437 - root                             (b2619688) :  INFO (signalr_client:105) - BAZARR trying to connect to Radarr SignalR feed...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/app/bazarr/bin/bazarr/signalr_client.py", line 108, in start
    self.connection.start()
  File "/app/bazarr/bin/bazarr/../libs/signalrcore/hub/base_hub_connection.py", line 44, in start
    return self.transport.start()
  File "/app/bazarr/bin/bazarr/../libs/signalrcore/transport/websockets/websocket_transport.py", line 62, in start
    self.negotiate()
  File "/app/bazarr/bin/bazarr/../libs/signalrcore/transport/websockets/websocket_transport.py", line 99, in negotiate
    raise HubError(response.status_code)\
signalrcore.hub.errors.UnAuthorizedHubError
2021-09-17T03:00:03Z <Greenlet at 0xb2619688: <bound method RadarrSignalrClient.start of <signalr_client.RadarrSignalrClient object at 0xb2604af0>>> failed with UnAuthorizedHubError
2021-09-17 03:00:03,458 - root                             (b6b61188) :  INFO (server:37) - BAZARR is started and waiting for request on http://0.0.0.0:6767
2021-09-17 03:02:38,722 - root                             (b232d358) :  ERROR (get_subtitle:519) - BAZARR Error saving Subtitles file to disk for this file:/movies/Mortal Kombat (2021)/Mortal.Kombat.2021.1080p.WEBRip.DD5.1.x264-CM.mkv
2021-09-17 03:05:49,637 - root                             (b232d9b8) :  ERROR (get_subtitle:519) - BAZARR Error saving Subtitles file to disk for this file:/movies/Mortal Kombat (2021)/Mortal.Kombat.2021.1080p.WEBRip.DD5.1.x264-CM.mkv
```

Should this works ?

===============================================

UPDATE

After give write permission to folder `~/LMDS/media/movies/Mortal Kombat (2021)` it worked. 
Does have one way to automate it without give generic permissions ?

**Comment by GreenFrogSB** [comment]
Permissions to resources should be controlled by owner not by script.
Script should not take control over these permissions.
